version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: truvis-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - truvis-network

  # Redis Commander (Redis 웹 UI - 선택사항)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: truvis-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - truvis-network

volumes:
  redis-data:
    driver: local

networks:
  truvis-network:
    driver: bridge
