# truvis 애플리케이션 설정
server:
  port: 8080

spring:
  application:
    name: truvis
    
  # 데이터베이스 설정 (개발용 H2)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # H2 콘솔 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Redis 설정
  redis:
    host: localhost
    port: 6379
    password: # 로컬 개발시 비밀번호 없음
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
        
# JWT 설정
jwt:
  secret: truvis-secret-key-for-jwt-token-generation-please-change-in-production-environment
  expiration: 86400000 # 24시간 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)

# 로깅 설정
logging:
  level:
    com.truvis: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
